room:
  usd_path: Assets/Room/Simple_Room_nolight/simple_room_nolight.usd
  scale: 0.5

ground:
  position_m: [0.0, 0.0, 0.015]
  size_m: [5.0, 5.0, 0.01]
  material_path: Assets/Material/material_0564/Wood_Tiles_Fineline.mdl
  static_friction: 0.8
  dynamic_friction: 0.8
  restitution: 0.0

table:
  position_m: [0.0, -0.05, 0.74]
  size_m: [1.4, 1.1, 0.05]
  material_path: Assets/Material/material_0122/Mahogany_Planks.mdl
  static_friction: 0.8
  dynamic_friction: 0.8
  restitution: 0.0

task_object_placement_area:
  x_range_m: [-0.65, 0.65]
  y_range_m: [-0.20, 0.45]

robot_mounts:
  left:
    position_xy_m: [-0.3, -0.45]
    orientation_xyzw: [0.0, 0.0, 0.70710678, 0.70710678]
  right:
    position_xy_m: [0.3, -0.45]
    orientation_xyzw: [0.0, 0.0, 0.70710678, 0.70710678]

camera:
  profile_path: ../cameras/d435.yml
  stand_usd_path: Assets/Object/Geometry/camera_stand/00000/object.usd
  stand_position_xy_m: [0.0, -0.47]
  stand_orientation_xyzw: [-0.70710678, 0.0, 0.0, 0.70710678]
  sensor_local_position_m: [0.06376095, 0.0003435, 0.75816412]
  sensor_local_orientation_xyzw: [0.18301278, -0.18301262, -0.68301276, 0.68301265]
  convention: opengl

lighting:
  texture_path: Assets/Background/brown_photostudio_02_4k.hdr
  intensity: 1000.0
