[project]
name = "learn-isaac"
version = "0.1.0"
description = "Learn Isaac"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "isaacsim[all,extscache]==6.0.1.0",
    "torch==2.11.0",
    "torchaudio==2.11.0",
    "torchvision==0.26.0",
    "modelscope",
    "isaaclab",
    "isaaclab-assets",
    "isaaclab-contrib",
    "isaaclab-mimic",
    "isaaclab-rl",
    "isaaclab-tasks",
    "nvidia-curobo[cu12]",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
isaacsim = { index = "nvidia" }
isaaclab = { path = "third_parties/IsaacLab/source/isaaclab", editable = true }
isaaclab-assets = { path = "third_parties/IsaacLab/source/isaaclab_assets", editable = true }
isaaclab-contrib = { path = "third_parties/IsaacLab/source/isaaclab_contrib", editable = true }
isaaclab-mimic = { path = "third_parties/IsaacLab/source/isaaclab_mimic", editable = true }
isaaclab-rl = { path = "third_parties/IsaacLab/source/isaaclab_rl", editable = true }
isaaclab-tasks = { path = "third_parties/IsaacLab/source/isaaclab_tasks", editable = true }
nvidia-curobo = { path = "third_parties/curobo", editable = true }

[tool.uv]
index-strategy = "unsafe-first-match"
prerelease = "allow"

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
