[project]
name = "learn-isaac"
version = "0.1.0"
description = "Learn Isaac"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "isaacsim[all,extscache]==6.0.1.0",
    "torch==2.10.0",
    "torchaudio==2.10.0",
    "torchvision==0.25.0",
    "modelscope",
    "isaaclab",
    "isaaclab-assets",
    "isaaclab-contrib",
    "isaaclab-experimental",
    "isaaclab-mimic",
    "isaaclab-newton[all]",
    "isaaclab-ov",
    "isaaclab-ovphysx",
    "isaaclab-physx[newton]",
    "isaaclab-ppisp",
    "isaaclab-rl[rsl-rl]",
    "isaaclab-tasks",
    "isaaclab-tasks-experimental",
    "isaaclab-visualizers",
    "pydantic",
    "pyyaml",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
isaacsim = { index = "nvidia" }
isaaclab = { path = "third_parties/IsaacLab/source/isaaclab", editable = true }
isaaclab-assets = { path = "third_parties/IsaacLab/source/isaaclab_assets", editable = true }
isaaclab-contrib = { path = "third_parties/IsaacLab/source/isaaclab_contrib", editable = true }
isaaclab-experimental = { path = "third_parties/IsaacLab/source/isaaclab_experimental", editable = true }
isaaclab-mimic = { path = "third_parties/IsaacLab/source/isaaclab_mimic", editable = true }
isaaclab-newton = { path = "third_parties/IsaacLab/source/isaaclab_newton", editable = true }
isaaclab-ov = { path = "third_parties/IsaacLab/source/isaaclab_ov", editable = true }
isaaclab-ovphysx = { path = "third_parties/IsaacLab/source/isaaclab_ovphysx", editable = true }
isaaclab-physx = { path = "third_parties/IsaacLab/source/isaaclab_physx", editable = true }
isaaclab-ppisp = { path = "third_parties/IsaacLab/source/isaaclab_ppisp", editable = true }
isaaclab-rl = { path = "third_parties/IsaacLab/source/isaaclab_rl", editable = true }
isaaclab-tasks = { path = "third_parties/IsaacLab/source/isaaclab_tasks", editable = true }
isaaclab-tasks-experimental = { path = "third_parties/IsaacLab/source/isaaclab_tasks_experimental", editable = true }
isaaclab-visualizers = { path = "third_parties/IsaacLab/source/isaaclab_visualizers", editable = true }

[tool.uv]
index-strategy = "unsafe-best-match"
prerelease = "allow"
override-dependencies = [
    "pin==4.0.0",
    "numpy==2.3.1",
    "pin-pink==4.2.0",
    "coverage==7.4.4",
    "torch==2.10.0",
    "torchaudio==2.10.0",
    "torchvision==0.25.0",
]
package = false

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
